/*===- TableGen'erated file -------------------------------------*- C++ -*-===*\
|*                                                                            *|
|* Intrinsic Function Source Fragment                                         *|
|*                                                                            *|
|* Automatically generated file, do not edit!                                 *|
|*                                                                            *|
\*===----------------------------------------------------------------------===*/

#ifndef LLVM_IR_INTRINSIC_SPV_ENUMS_H
#define LLVM_IR_INTRINSIC_SPV_ENUMS_H

namespace llvm::Intrinsic {

enum SPVIntrinsics : unsigned {
// Enum values for intrinsics.
    spv_all = 13070,                                   // llvm.spv.all (IntrinsicsSPIRV.td:95)
    spv_alloca,                                // llvm.spv.alloca (IntrinsicsSPIRV.td:42)
    spv_alloca_array,                          // llvm.spv.alloca.array (IntrinsicsSPIRV.td:43)
    spv_any,                                   // llvm.spv.any (IntrinsicsSPIRV.td:96)
    spv_assign_aliasing_decoration,            // llvm.spv.assign.aliasing.decoration (IntrinsicsSPIRV.td:333)
    spv_assign_decoration,                     // llvm.spv.assign.decoration (IntrinsicsSPIRV.td:19)
    spv_assign_fpmaxerror_decoration,          // llvm.spv.assign.fpmaxerror.decoration (IntrinsicsSPIRV.td:336)
    spv_assign_name,                           // llvm.spv.assign.name (IntrinsicsSPIRV.td:18)
    spv_assign_ptr_type,                       // llvm.spv.assign.ptr.type (IntrinsicsSPIRV.td:17)
    spv_assign_type,                           // llvm.spv.assign.type (IntrinsicsSPIRV.td:16)
    spv_assume,                                // llvm.spv.assume (IntrinsicsSPIRV.td:61)
    spv_bitcast,                               // llvm.spv.bitcast (IntrinsicsSPIRV.td:34)
    spv_cmpxchg,                               // llvm.spv.cmpxchg (IntrinsicsSPIRV.td:40)
    spv_const_composite,                       // llvm.spv.const.composite (IntrinsicsSPIRV.td:33)
    spv_cross,                                 // llvm.spv.cross (IntrinsicsSPIRV.td:97)
    spv_ddx,                                   // llvm.spv.ddx (IntrinsicsSPIRV.td:164)
    spv_ddx_coarse,                            // llvm.spv.ddx.coarse (IntrinsicsSPIRV.td:166)
    spv_ddx_fine,                              // llvm.spv.ddx.fine (IntrinsicsSPIRV.td:168)
    spv_ddy,                                   // llvm.spv.ddy (IntrinsicsSPIRV.td:165)
    spv_ddy_coarse,                            // llvm.spv.ddy.coarse (IntrinsicsSPIRV.td:167)
    spv_ddy_fine,                              // llvm.spv.ddy.fine (IntrinsicsSPIRV.td:169)
    spv_degrees,                               // llvm.spv.degrees (IntrinsicsSPIRV.td:98)
    spv_discard,                               // llvm.spv.discard (IntrinsicsSPIRV.td:163)
    spv_distance,                              // llvm.spv.distance (IntrinsicsSPIRV.td:99)
    spv_dot4add_i8packed,                      // llvm.spv.dot4add.i8packed (IntrinsicsSPIRV.td:132)
    spv_dot4add_u8packed,                      // llvm.spv.dot4add.u8packed (IntrinsicsSPIRV.td:133)
    spv_expect,                                // llvm.spv.expect (IntrinsicsSPIRV.td:62)
    spv_extractelt,                            // llvm.spv.extractelt (IntrinsicsSPIRV.td:31)
    spv_extractv,                              // llvm.spv.extractv (IntrinsicsSPIRV.td:29)
    spv_faceforward,                           // llvm.spv.faceforward (IntrinsicsSPIRV.td:100)
    spv_fdot,                                  // llvm.spv.fdot (IntrinsicsSPIRV.td:120)
    spv_firstbitlow,                           // llvm.spv.firstbitlow (IntrinsicsSPIRV.td:200)
    spv_firstbitshigh,                         // llvm.spv.firstbitshigh (IntrinsicsSPIRV.td:199)
    spv_firstbituhigh,                         // llvm.spv.firstbituhigh (IntrinsicsSPIRV.td:198)
    spv_flattened_thread_id_in_group,          // llvm.spv.flattened.thread.id.in.group (IntrinsicsSPIRV.td:94)
    spv_frac,                                  // llvm.spv.frac (IntrinsicsSPIRV.td:101)
    spv_fwidth,                                // llvm.spv.fwidth (IntrinsicsSPIRV.td:170)
    spv_generic_cast_to_ptr_explicit,          // llvm.spv.generic.cast.to.ptr.explicit (IntrinsicsSPIRV.td:339)
    spv_gep,                                   // llvm.spv.gep (IntrinsicsSPIRV.td:26)
    spv_global_offset,                         // llvm.spv.global.offset (IntrinsicsSPIRV.td:82)
    spv_global_size,                           // llvm.spv.global.size (IntrinsicsSPIRV.td:81)
    spv_group_id,                              // llvm.spv.group.id (IntrinsicsSPIRV.td:78)
    spv_group_memory_barrier,                  // llvm.spv.group.memory.barrier (IntrinsicsSPIRV.td:160)
    spv_group_memory_barrier_with_group_sync,  // llvm.spv.group.memory.barrier.with.group.sync (IntrinsicsSPIRV.td:161)
    spv_init_global,                           // llvm.spv.init.global (IntrinsicsSPIRV.td:23)
    spv_inline_asm,                            // llvm.spv.inline.asm (IntrinsicsSPIRV.td:45)
    spv_insertelt,                             // llvm.spv.insertelt (IntrinsicsSPIRV.td:32)
    spv_insertv,                               // llvm.spv.insertv (IntrinsicsSPIRV.td:30)
    spv_isinf,                                 // llvm.spv.isinf (IntrinsicsSPIRV.td:102)
    spv_isnan,                                 // llvm.spv.isnan (IntrinsicsSPIRV.td:104)
    spv_length,                                // llvm.spv.length (IntrinsicsSPIRV.td:108)
    spv_lerp,                                  // llvm.spv.lerp (IntrinsicsSPIRV.td:106)
    spv_lifetime_end,                          // llvm.spv.lifetime.end (IntrinsicsSPIRV.td:70)
    spv_lifetime_start,                        // llvm.spv.lifetime.start (IntrinsicsSPIRV.td:65)
    spv_load,                                  // llvm.spv.load (IntrinsicsSPIRV.td:27)
    spv_loop_control_intel,                    // llvm.spv.loop.control.intel (IntrinsicsSPIRV.td:38)
    spv_loop_merge,                            // llvm.spv.loop.merge (IntrinsicsSPIRV.td:37)
    spv_masked_gather,                         // llvm.spv.masked.gather (IntrinsicsSPIRV.td:53)
    spv_masked_scatter,                        // llvm.spv.masked.scatter (IntrinsicsSPIRV.td:56)
    spv_named_boolean_spec_constant,           // llvm.spv.named.boolean.spec.constant (IntrinsicsSPIRV.td:46)
    spv_nclamp,                                // llvm.spv.nclamp (IntrinsicsSPIRV.td:173)
    spv_normalize,                             // llvm.spv.normalize (IntrinsicsSPIRV.td:109)
    spv_num_subgroups,                         // llvm.spv.num.subgroups (IntrinsicsSPIRV.td:86)
    spv_num_workgroups,                        // llvm.spv.num.workgroups (IntrinsicsSPIRV.td:83)
    spv_packhalf2x16,                          // llvm.spv.packhalf2x16 (IntrinsicsSPIRV.td:344)
    spv_ptrcast,                               // llvm.spv.ptrcast (IntrinsicsSPIRV.td:35)
    spv_pushconstant_getpointer,               // llvm.spv.pushconstant.getpointer (IntrinsicsSPIRV.td:315)
    spv_quad_read_across_x,                    // llvm.spv.quad.read.across.x (IntrinsicsSPIRV.td:156)
    spv_quad_read_across_y,                    // llvm.spv.quad.read.across.y (IntrinsicsSPIRV.td:157)
    spv_radians,                               // llvm.spv.radians (IntrinsicsSPIRV.td:159)
    spv_reflect,                               // llvm.spv.reflect (IntrinsicsSPIRV.td:110)
    spv_refract,                               // llvm.spv.refract (IntrinsicsSPIRV.td:111)
    spv_resource_calculate_lod,                // llvm.spv.resource.calculate.lod (IntrinsicsSPIRV.td:289)
    spv_resource_calculate_lod_unclamped,      // llvm.spv.resource.calculate.lod.unclamped (IntrinsicsSPIRV.td:294)
    spv_resource_counterhandlefrombinding,     // llvm.spv.resource.counterhandlefrombinding (IntrinsicsSPIRV.td:193)
    spv_resource_counterhandlefromimplicitbinding,  // llvm.spv.resource.counterhandlefromimplicitbinding (IntrinsicsSPIRV.td:189)
    spv_resource_gather,                       // llvm.spv.resource.gather (IntrinsicsSPIRV.td:299)
    spv_resource_gather_cmp,                   // llvm.spv.resource.gather.cmp (IntrinsicsSPIRV.td:305)
    spv_resource_getdimensions_levels_x,       // llvm.spv.resource.getdimensions.levels.x (IntrinsicsSPIRV.td:212)
    spv_resource_getdimensions_levels_xy,      // llvm.spv.resource.getdimensions.levels.xy (IntrinsicsSPIRV.td:214)
    spv_resource_getdimensions_levels_xyz,     // llvm.spv.resource.getdimensions.levels.xyz (IntrinsicsSPIRV.td:216)
    spv_resource_getdimensions_ms_xy,          // llvm.spv.resource.getdimensions.ms.xy (IntrinsicsSPIRV.td:218)
    spv_resource_getdimensions_ms_xyz,         // llvm.spv.resource.getdimensions.ms.xyz (IntrinsicsSPIRV.td:220)
    spv_resource_getdimensions_x,              // llvm.spv.resource.getdimensions.x (IntrinsicsSPIRV.td:206)
    spv_resource_getdimensions_xy,             // llvm.spv.resource.getdimensions.xy (IntrinsicsSPIRV.td:208)
    spv_resource_getdimensions_xyz,            // llvm.spv.resource.getdimensions.xyz (IntrinsicsSPIRV.td:210)
    spv_resource_getpointer,                   // llvm.spv.resource.getpointer (IntrinsicsSPIRV.td:311)
    spv_resource_handlefrombinding,            // llvm.spv.resource.handlefrombinding (IntrinsicsSPIRV.td:179)
    spv_resource_handlefromimplicitbinding,    // llvm.spv.resource.handlefromimplicitbinding (IntrinsicsSPIRV.td:184)
    spv_resource_load_level,                   // llvm.spv.resource.load.level (IntrinsicsSPIRV.td:265)
    spv_resource_load_typedbuffer,             // llvm.spv.resource.load.typedbuffer (IntrinsicsSPIRV.td:324)
    spv_resource_nonuniformindex,              // llvm.spv.resource.nonuniformindex (IntrinsicsSPIRV.td:318)
    spv_resource_sample,                       // llvm.spv.resource.sample (IntrinsicsSPIRV.td:223)
    spv_resource_sample_clamp,                 // llvm.spv.resource.sample.clamp (IntrinsicsSPIRV.td:228)
    spv_resource_samplebias,                   // llvm.spv.resource.samplebias (IntrinsicsSPIRV.td:234)
    spv_resource_samplebias_clamp,             // llvm.spv.resource.samplebias.clamp (IntrinsicsSPIRV.td:240)
    spv_resource_samplecmp,                    // llvm.spv.resource.samplecmp (IntrinsicsSPIRV.td:271)
    spv_resource_samplecmp_clamp,              // llvm.spv.resource.samplecmp.clamp (IntrinsicsSPIRV.td:277)
    spv_resource_samplecmplevelzero,           // llvm.spv.resource.samplecmplevelzero (IntrinsicsSPIRV.td:283)
    spv_resource_samplegrad,                   // llvm.spv.resource.samplegrad (IntrinsicsSPIRV.td:246)
    spv_resource_samplegrad_clamp,             // llvm.spv.resource.samplegrad.clamp (IntrinsicsSPIRV.td:252)
    spv_resource_samplelevel,                  // llvm.spv.resource.samplelevel (IntrinsicsSPIRV.td:259)
    spv_resource_store_typedbuffer,            // llvm.spv.resource.store.typedbuffer (IntrinsicsSPIRV.td:329)
    spv_resource_updatecounter,                // llvm.spv.resource.updatecounter (IntrinsicsSPIRV.td:202)
    spv_rsqrt,                                 // llvm.spv.rsqrt (IntrinsicsSPIRV.td:116)
    spv_saturate,                              // llvm.spv.saturate (IntrinsicsSPIRV.td:117)
    spv_sclamp,                                // llvm.spv.sclamp (IntrinsicsSPIRV.td:172)
    spv_sdot,                                  // llvm.spv.sdot (IntrinsicsSPIRV.td:124)
    spv_selection_merge,                       // llvm.spv.selection.merge (IntrinsicsSPIRV.td:39)
    spv_sign,                                  // llvm.spv.sign (IntrinsicsSPIRV.td:158)
    spv_smoothstep,                            // llvm.spv.smoothstep (IntrinsicsSPIRV.td:118)
    spv_step,                                  // llvm.spv.step (IntrinsicsSPIRV.td:119)
    spv_store,                                 // llvm.spv.store (IntrinsicsSPIRV.td:28)
    spv_subgroup_ballot,                       // llvm.spv.subgroup.ballot (IntrinsicsSPIRV.td:142)
    spv_subgroup_id,                           // llvm.spv.subgroup.id (IntrinsicsSPIRV.td:88)
    spv_subgroup_local_invocation_id,          // llvm.spv.subgroup.local.invocation.id (IntrinsicsSPIRV.td:90)
    spv_subgroup_max_size,                     // llvm.spv.subgroup.max.size (IntrinsicsSPIRV.td:92)
    spv_subgroup_prefix_bit_count,             // llvm.spv.subgroup.prefix.bit.count (IntrinsicsSPIRV.td:134)
    spv_subgroup_size,                         // llvm.spv.subgroup.size (IntrinsicsSPIRV.td:84)
    spv_switch,                                // llvm.spv.switch (IntrinsicsSPIRV.td:36)
    spv_thread_id,                             // llvm.spv.thread.id (IntrinsicsSPIRV.td:77)
    spv_thread_id_in_group,                    // llvm.spv.thread.id.in.group (IntrinsicsSPIRV.td:79)
    spv_track_constant,                        // llvm.spv.track.constant (IntrinsicsSPIRV.td:22)
    spv_uclamp,                                // llvm.spv.uclamp (IntrinsicsSPIRV.td:171)
    spv_udot,                                  // llvm.spv.udot (IntrinsicsSPIRV.td:128)
    spv_undef,                                 // llvm.spv.undef (IntrinsicsSPIRV.td:44)
    spv_unpackhalf2x16,                        // llvm.spv.unpackhalf2x16 (IntrinsicsSPIRV.td:343)
    spv_unreachable,                           // llvm.spv.unreachable (IntrinsicsSPIRV.td:41)
    spv_unref_global,                          // llvm.spv.unref.global (IntrinsicsSPIRV.td:24)
    spv_value_md,                              // llvm.spv.value.md (IntrinsicsSPIRV.td:20)
    spv_wave_active_countbits,                 // llvm.spv.wave.active.countbits (IntrinsicsSPIRV.td:135)
    spv_wave_all,                              // llvm.spv.wave.all (IntrinsicsSPIRV.td:137)
    spv_wave_all_equal,                        // llvm.spv.wave.all.equal (IntrinsicsSPIRV.td:136)
    spv_wave_any,                              // llvm.spv.wave.any (IntrinsicsSPIRV.td:138)
    spv_wave_get_lane_count,                   // llvm.spv.wave.get.lane.count (IntrinsicsSPIRV.td:152)
    spv_wave_is_first_lane,                    // llvm.spv.wave.is.first.lane (IntrinsicsSPIRV.td:150)
    spv_wave_prefix_product,                   // llvm.spv.wave.prefix.product (IntrinsicsSPIRV.td:155)
    spv_wave_prefix_sum,                       // llvm.spv.wave.prefix.sum (IntrinsicsSPIRV.td:154)
    spv_wave_product,                          // llvm.spv.wave.product (IntrinsicsSPIRV.td:149)
    spv_wave_readlane,                         // llvm.spv.wave.readlane (IntrinsicsSPIRV.td:151)
    spv_wave_reduce_and,                       // llvm.spv.wave.reduce.and (IntrinsicsSPIRV.td:141)
    spv_wave_reduce_max,                       // llvm.spv.wave.reduce.max (IntrinsicsSPIRV.td:145)
    spv_wave_reduce_min,                       // llvm.spv.wave.reduce.min (IntrinsicsSPIRV.td:146)
    spv_wave_reduce_or,                        // llvm.spv.wave.reduce.or (IntrinsicsSPIRV.td:139)
    spv_wave_reduce_sum,                       // llvm.spv.wave.reduce.sum (IntrinsicsSPIRV.td:148)
    spv_wave_reduce_umax,                      // llvm.spv.wave.reduce.umax (IntrinsicsSPIRV.td:144)
    spv_wave_reduce_umin,                      // llvm.spv.wave.reduce.umin (IntrinsicsSPIRV.td:147)
    spv_wave_reduce_xor,                       // llvm.spv.wave.reduce.xor (IntrinsicsSPIRV.td:140)
    spv_workgroup_size,                        // llvm.spv.workgroup.size (IntrinsicsSPIRV.td:80)
}; // enum

} // namespace llvm::Intrinsic

#endif // LLVM_IR_INTRINSIC_SPV_ENUMS_H

