/*===- TableGen'erated file -------------------------------------*- C++ -*-===*\
|*                                                                            *|
|* Intrinsic Function Source Fragment                                         *|
|*                                                                            *|
|* Automatically generated file, do not edit!                                 *|
|*                                                                            *|
\*===----------------------------------------------------------------------===*/

#ifndef LLVM_IR_INTRINSIC_DX_ENUMS_H
#define LLVM_IR_INTRINSIC_DX_ENUMS_H

namespace llvm::Intrinsic {

enum DXIntrinsics : unsigned {
// Enum values for intrinsics.
    dx_all = 4219,                                    // llvm.dx.all (IntrinsicsDirectX.td:176)
    dx_any,                                    // llvm.dx.any (IntrinsicsDirectX.td:177)
    dx_asdouble,                               // llvm.dx.asdouble (IntrinsicsDirectX.td:178)
    dx_cross,                                  // llvm.dx.cross (IntrinsicsDirectX.td:182)
    dx_ddx_coarse,                             // llvm.dx.ddx.coarse (IntrinsicsDirectX.td:280)
    dx_ddx_fine,                               // llvm.dx.ddx.fine (IntrinsicsDirectX.td:282)
    dx_ddy_coarse,                             // llvm.dx.ddy.coarse (IntrinsicsDirectX.td:281)
    dx_ddy_fine,                               // llvm.dx.ddy.fine (IntrinsicsDirectX.td:283)
    dx_degrees,                                // llvm.dx.degrees (IntrinsicsDirectX.td:226)
    dx_discard,                                // llvm.dx.discard (IntrinsicsDirectX.td:279)
    dx_dot2,                                   // llvm.dx.dot2 (IntrinsicsDirectX.td:185)
    dx_dot2add,                                // llvm.dx.dot2add (IntrinsicsDirectX.td:218)
    dx_dot3,                                   // llvm.dx.dot3 (IntrinsicsDirectX.td:191)
    dx_dot4,                                   // llvm.dx.dot4 (IntrinsicsDirectX.td:198)
    dx_dot4add_i8packed,                       // llvm.dx.dot4add.i8packed (IntrinsicsDirectX.td:222)
    dx_dot4add_u8packed,                       // llvm.dx.dot4add.u8packed (IntrinsicsDirectX.td:223)
    dx_fdot,                                   // llvm.dx.fdot (IntrinsicsDirectX.td:206)
    dx_firstbitlow,                            // llvm.dx.firstbitlow (IntrinsicsDirectX.td:286)
    dx_firstbitshigh,                          // llvm.dx.firstbitshigh (IntrinsicsDirectX.td:285)
    dx_firstbituhigh,                          // llvm.dx.firstbituhigh (IntrinsicsDirectX.td:284)
    dx_flattened_thread_id_in_group,           // llvm.dx.flattened.thread.id.in.group (IntrinsicsDirectX.td:18)
    dx_frac,                                   // llvm.dx.frac (IntrinsicsDirectX.td:225)
    dx_group_id,                               // llvm.dx.group.id (IntrinsicsDirectX.td:16)
    dx_group_memory_barrier,                   // llvm.dx.group.memory.barrier (IntrinsicsDirectX.td:288)
    dx_group_memory_barrier_with_group_sync,   // llvm.dx.group.memory.barrier.with.group.sync (IntrinsicsDirectX.td:291)
    dx_imad,                                   // llvm.dx.imad (IntrinsicsDirectX.td:242)
    dx_isinf,                                  // llvm.dx.isinf (IntrinsicsDirectX.td:228)
    dx_isnan,                                  // llvm.dx.isnan (IntrinsicsDirectX.td:230)
    dx_legacyf16tof32,                         // llvm.dx.legacyf16tof32 (IntrinsicsDirectX.td:233)
    dx_legacyf32tof16,                         // llvm.dx.legacyf32tof16 (IntrinsicsDirectX.td:236)
    dx_lerp,                                   // llvm.dx.lerp (IntrinsicsDirectX.td:239)
    dx_load_input,                             // llvm.dx.load.input (IntrinsicsDirectX.td:294)
    dx_nclamp,                                 // llvm.dx.nclamp (IntrinsicsDirectX.td:181)
    dx_normalize,                              // llvm.dx.normalize (IntrinsicsDirectX.td:244)
    dx_quad_read_across_x,                     // llvm.dx.quad.read.across.x (IntrinsicsDirectX.td:272)
    dx_quad_read_across_y,                     // llvm.dx.quad.read.across.y (IntrinsicsDirectX.td:273)
    dx_radians,                                // llvm.dx.radians (IntrinsicsDirectX.td:278)
    dx_resource_calculate_lod,                 // llvm.dx.resource.calculate.lod (IntrinsicsDirectX.td:133)
    dx_resource_calculate_lod_unclamped,       // llvm.dx.resource.calculate.lod.unclamped (IntrinsicsDirectX.td:138)
    dx_resource_casthandle,                    // llvm.dx.resource.casthandle (IntrinsicsDirectX.td:174)
    dx_resource_gather,                        // llvm.dx.resource.gather (IntrinsicsDirectX.td:161)
    dx_resource_gather_cmp,                    // llvm.dx.resource.gather.cmp (IntrinsicsDirectX.td:167)
    dx_resource_getdimensions_levels_xy,       // llvm.dx.resource.getdimensions.levels.xy (IntrinsicsDirectX.td:84)
    dx_resource_getdimensions_x,               // llvm.dx.resource.getdimensions.x (IntrinsicsDirectX.td:80)
    dx_resource_getdimensions_xy,              // llvm.dx.resource.getdimensions.xy (IntrinsicsDirectX.td:82)
    dx_resource_getpointer,                    // llvm.dx.resource.getpointer (IntrinsicsDirectX.td:39)
    dx_resource_handlefrombinding,             // llvm.dx.resource.handlefrombinding (IntrinsicsDirectX.td:24)
    dx_resource_handlefromimplicitbinding,     // llvm.dx.resource.handlefromimplicitbinding (IntrinsicsDirectX.td:33)
    dx_resource_load_cbufferrow_2,             // llvm.dx.resource.load.cbufferrow.2 (IntrinsicsDirectX.td:72)
    dx_resource_load_cbufferrow_4,             // llvm.dx.resource.load.cbufferrow.4 (IntrinsicsDirectX.td:68)
    dx_resource_load_cbufferrow_8,             // llvm.dx.resource.load.cbufferrow.8 (IntrinsicsDirectX.td:63)
    dx_resource_load_level,                    // llvm.dx.resource.load.level (IntrinsicsDirectX.td:127)
    dx_resource_load_rawbuffer,                // llvm.dx.resource.load.rawbuffer (IntrinsicsDirectX.td:52)
    dx_resource_load_typedbuffer,              // llvm.dx.resource.load.typedbuffer (IntrinsicsDirectX.td:46)
    dx_resource_nonuniformindex,               // llvm.dx.resource.nonuniformindex (IntrinsicsDirectX.td:43)
    dx_resource_sample,                        // llvm.dx.resource.sample (IntrinsicsDirectX.td:87)
    dx_resource_sample_clamp,                  // llvm.dx.resource.sample.clamp (IntrinsicsDirectX.td:92)
    dx_resource_samplebias,                    // llvm.dx.resource.samplebias (IntrinsicsDirectX.td:97)
    dx_resource_samplebias_clamp,              // llvm.dx.resource.samplebias.clamp (IntrinsicsDirectX.td:103)
    dx_resource_samplecmp,                     // llvm.dx.resource.samplecmp (IntrinsicsDirectX.td:143)
    dx_resource_samplecmp_clamp,               // llvm.dx.resource.samplecmp.clamp (IntrinsicsDirectX.td:149)
    dx_resource_samplecmplevelzero,            // llvm.dx.resource.samplecmplevelzero (IntrinsicsDirectX.td:155)
    dx_resource_samplegrad,                    // llvm.dx.resource.samplegrad (IntrinsicsDirectX.td:109)
    dx_resource_samplegrad_clamp,              // llvm.dx.resource.samplegrad.clamp (IntrinsicsDirectX.td:115)
    dx_resource_samplelevel,                   // llvm.dx.resource.samplelevel (IntrinsicsDirectX.td:121)
    dx_resource_store_rawbuffer,               // llvm.dx.resource.store.rawbuffer (IntrinsicsDirectX.td:56)
    dx_resource_store_typedbuffer,             // llvm.dx.resource.store.typedbuffer (IntrinsicsDirectX.td:49)
    dx_resource_updatecounter,                 // llvm.dx.resource.updatecounter (IntrinsicsDirectX.td:76)
    dx_rsqrt,                                  // llvm.dx.rsqrt (IntrinsicsDirectX.td:246)
    dx_saturate,                               // llvm.dx.saturate (IntrinsicsDirectX.td:183)
    dx_sclamp,                                 // llvm.dx.sclamp (IntrinsicsDirectX.td:180)
    dx_sdot,                                   // llvm.dx.sdot (IntrinsicsDirectX.td:210)
    dx_sign,                                   // llvm.dx.sign (IntrinsicsDirectX.td:274)
    dx_splitdouble,                            // llvm.dx.splitdouble (IntrinsicsDirectX.td:276)
    dx_step,                                   // llvm.dx.step (IntrinsicsDirectX.td:275)
    dx_store_output,                           // llvm.dx.store.output (IntrinsicsDirectX.td:300)
    dx_thread_id,                              // llvm.dx.thread.id (IntrinsicsDirectX.td:15)
    dx_thread_id_in_group,                     // llvm.dx.thread.id.in.group (IntrinsicsDirectX.td:17)
    dx_uclamp,                                 // llvm.dx.uclamp (IntrinsicsDirectX.td:179)
    dx_udot,                                   // llvm.dx.udot (IntrinsicsDirectX.td:214)
    dx_umad,                                   // llvm.dx.umad (IntrinsicsDirectX.td:243)
    dx_wave_active_countbits,                  // llvm.dx.wave.active.countbits (IntrinsicsDirectX.td:247)
    dx_wave_all,                               // llvm.dx.wave.all (IntrinsicsDirectX.td:249)
    dx_wave_all_equal,                         // llvm.dx.wave.all.equal (IntrinsicsDirectX.td:248)
    dx_wave_any,                               // llvm.dx.wave.any (IntrinsicsDirectX.td:250)
    dx_wave_ballot,                            // llvm.dx.wave.ballot (IntrinsicsDirectX.td:251)
    dx_wave_get_lane_count,                    // llvm.dx.wave.get.lane.count (IntrinsicsDirectX.td:266)
    dx_wave_getlaneindex,                      // llvm.dx.wave.getlaneindex (IntrinsicsDirectX.td:252)
    dx_wave_is_first_lane,                     // llvm.dx.wave.is.first.lane (IntrinsicsDirectX.td:264)
    dx_wave_prefix_bit_count,                  // llvm.dx.wave.prefix.bit.count (IntrinsicsDirectX.td:245)
    dx_wave_prefix_product,                    // llvm.dx.wave.prefix.product (IntrinsicsDirectX.td:270)
    dx_wave_prefix_sum,                        // llvm.dx.wave.prefix.sum (IntrinsicsDirectX.td:268)
    dx_wave_prefix_uproduct,                   // llvm.dx.wave.prefix.uproduct (IntrinsicsDirectX.td:271)
    dx_wave_prefix_usum,                       // llvm.dx.wave.prefix.usum (IntrinsicsDirectX.td:269)
    dx_wave_product,                           // llvm.dx.wave.product (IntrinsicsDirectX.td:262)
    dx_wave_readlane,                          // llvm.dx.wave.readlane (IntrinsicsDirectX.td:265)
    dx_wave_reduce_and,                        // llvm.dx.wave.reduce.and (IntrinsicsDirectX.td:255)
    dx_wave_reduce_max,                        // llvm.dx.wave.reduce.max (IntrinsicsDirectX.td:256)
    dx_wave_reduce_min,                        // llvm.dx.wave.reduce.min (IntrinsicsDirectX.td:258)
    dx_wave_reduce_or,                         // llvm.dx.wave.reduce.or (IntrinsicsDirectX.td:253)
    dx_wave_reduce_sum,                        // llvm.dx.wave.reduce.sum (IntrinsicsDirectX.td:260)
    dx_wave_reduce_umax,                       // llvm.dx.wave.reduce.umax (IntrinsicsDirectX.td:257)
    dx_wave_reduce_umin,                       // llvm.dx.wave.reduce.umin (IntrinsicsDirectX.td:259)
    dx_wave_reduce_usum,                       // llvm.dx.wave.reduce.usum (IntrinsicsDirectX.td:261)
    dx_wave_reduce_xor,                        // llvm.dx.wave.reduce.xor (IntrinsicsDirectX.td:254)
    dx_wave_uproduct,                          // llvm.dx.wave.uproduct (IntrinsicsDirectX.td:263)
}; // enum

} // namespace llvm::Intrinsic

#endif // LLVM_IR_INTRINSIC_DX_ENUMS_H

