// RISCV Vector builtin enumerators
#ifdef GET_RISCVV_BUILTIN_ENUMERATORS
  BI__builtin_rvv_sf_vqmaccu_2x8x2,
  BI__builtin_rvv_sf_vqmaccu_2x8x2_tu,
  BI__builtin_rvv_sf_vc_v_x,
  BI__builtin_rvv_sf_vc_x_se,
  BI__builtin_rvv_sf_vc_i_se,
  BI__builtin_rvv_sf_vc_xv_se,
  BI__builtin_rvv_sf_vc_iv_se,
  BI__builtin_rvv_sf_vc_vv_se,
  BI__builtin_rvv_sf_vc_fv_se,
  BI__builtin_rvv_sf_vc_xvv_se,
  BI__builtin_rvv_sf_vc_ivv_se,
  BI__builtin_rvv_sf_vc_vvv_se,
  BI__builtin_rvv_sf_vc_fvv_se,
  BI__builtin_rvv_sf_vc_v_x_se,
  BI__builtin_rvv_sf_vc_v_i,
  BI__builtin_rvv_sf_vc_v_i_se,
  BI__builtin_rvv_sf_vc_v_xv,
  BI__builtin_rvv_sf_vc_v_xv_se,
  BI__builtin_rvv_sf_vc_v_iv,
  BI__builtin_rvv_sf_vc_v_iv_se,
  BI__builtin_rvv_sf_vc_v_vv,
  BI__builtin_rvv_sf_vc_v_vv_se,
  BI__builtin_rvv_sf_vc_v_fv,
  BI__builtin_rvv_sf_vc_v_fv_se,
  BI__builtin_rvv_sf_vc_v_xvv,
  BI__builtin_rvv_sf_vc_v_xvv_se,
  BI__builtin_rvv_sf_vc_v_ivv,
  BI__builtin_rvv_sf_vc_v_ivv_se,
  BI__builtin_rvv_sf_vc_v_vvv,
  BI__builtin_rvv_sf_vc_v_vvv_se,
  BI__builtin_rvv_sf_vc_v_fvv,
  BI__builtin_rvv_sf_vc_v_fvv_se,
  BI__builtin_rvv_sf_vc_xvw_se,
  BI__builtin_rvv_sf_vc_ivw_se,
  BI__builtin_rvv_sf_vc_vvw_se,
  BI__builtin_rvv_sf_vc_fvw_se,
  BI__builtin_rvv_sf_vc_v_xvw,
  BI__builtin_rvv_sf_vc_v_xvw_se,
  BI__builtin_rvv_sf_vc_v_ivw,
  BI__builtin_rvv_sf_vc_v_ivw_se,
  BI__builtin_rvv_sf_vc_v_vvw,
  BI__builtin_rvv_sf_vc_v_vvw_se,
  BI__builtin_rvv_sf_vc_v_fvw,
  BI__builtin_rvv_sf_vc_v_fvw_se,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf_rm,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf_rm_tu,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf_rm_m,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf_rm_tum,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf_rm_tumu,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf_rm_mu,
  BI__builtin_rvv_sf_vqmacc_2x8x2,
  BI__builtin_rvv_sf_vqmacc_2x8x2_tu,
  BI__builtin_rvv_sf_vqmaccus_2x8x2,
  BI__builtin_rvv_sf_vqmaccus_2x8x2_tu,
  BI__builtin_rvv_sf_vqmaccsu_2x8x2,
  BI__builtin_rvv_sf_vqmaccsu_2x8x2_tu,
  BI__builtin_rvv_sf_vqmaccu_4x8x4,
  BI__builtin_rvv_sf_vqmaccu_4x8x4_tu,
  BI__builtin_rvv_sf_vqmacc_4x8x4,
  BI__builtin_rvv_sf_vqmacc_4x8x4_tu,
  BI__builtin_rvv_sf_vqmaccus_4x8x4,
  BI__builtin_rvv_sf_vqmaccus_4x8x4_tu,
  BI__builtin_rvv_sf_vqmaccsu_4x8x4,
  BI__builtin_rvv_sf_vqmaccsu_4x8x4_tu,
  BI__builtin_rvv_sf_vfexp_v,
  BI__builtin_rvv_sf_vfexp_v_tu,
  BI__builtin_rvv_sf_vfexp_v_m,
  BI__builtin_rvv_sf_vfexp_v_tum,
  BI__builtin_rvv_sf_vfexp_v_tumu,
  BI__builtin_rvv_sf_vfexp_v_mu,
  BI__builtin_rvv_sf_vfexpa_v,
  BI__builtin_rvv_sf_vfexpa_v_tu,
  BI__builtin_rvv_sf_vfexpa_v_m,
  BI__builtin_rvv_sf_vfexpa_v_tum,
  BI__builtin_rvv_sf_vfexpa_v_tumu,
  BI__builtin_rvv_sf_vfexpa_v_mu,
  BI__builtin_rvv_sf_vfwmacc_4x4x4,
  BI__builtin_rvv_sf_vfwmacc_4x4x4_tu,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf_rm,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf_rm_tu,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf_rm_m,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf_rm_tum,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf_rm_tumu,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf_rm_mu,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf_tu,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf_m,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf_tum,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf_tumu,
  BI__builtin_rvv_sf_vfnrclip_x_f_qf_mu,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf_tu,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf_m,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf_tum,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf_tumu,
  BI__builtin_rvv_sf_vfnrclip_xu_f_qf_mu,
  BI__builtin_rvv_sf_vlte8,
  BI__builtin_rvv_sf_vtmv_v_t,
  BI__builtin_rvv_sf_vtzero_t,
  BI__builtin_rvv_sf_vtdiscard,
  BI__builtin_rvv_sf_vtmv_t_v,
  BI__builtin_rvv_sf_vlte16,
  BI__builtin_rvv_sf_vlte32,
  BI__builtin_rvv_sf_vlte64,
  BI__builtin_rvv_sf_vste8,
  BI__builtin_rvv_sf_vste16,
  BI__builtin_rvv_sf_vste32,
  BI__builtin_rvv_sf_vste64,
  BI__builtin_rvv_sf_mm_u_u_w4,
  BI__builtin_rvv_sf_mm_s_u_w4,
  BI__builtin_rvv_sf_mm_u_s_w4,
  BI__builtin_rvv_sf_mm_s_s_w4,
  BI__builtin_rvv_sf_mm_f_f_w2,
  BI__builtin_rvv_sf_mm_f_f_w1,
  BI__builtin_rvv_sf_mm_e5m2_e5m2_w4,
  BI__builtin_rvv_sf_mm_e5m2_e4m3_w4,
  BI__builtin_rvv_sf_mm_e4m3_e5m2_w4,
  BI__builtin_rvv_sf_mm_e4m3_e4m3_w4,
  BI__builtin_rvv_sf_vsettk,
  BI__builtin_rvv_sf_vsettm,
  BI__builtin_rvv_sf_vsettn,
  BI__builtin_rvv_sf_vsettnt,
#endif // GET_RISCVV_BUILTIN_ENUMERATORS

// RISCV Vector builtin enumerators
#ifdef GET_RISCVV_BUILTIN_STR_TABLE

#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Woverlength-strings"
#endif
static constexpr char BuiltinStringsStorage[] =
  "\0"
  "n\0"
  "zve32x\0"
  "sf_vqmaccu_2x8x2\0"
  "sf_vqmaccu_2x8x2_tu\0"
  "sf_vc_v_x\0"
  "sf_vc_x_se\0"
  "sf_vc_i_se\0"
  "sf_vc_xv_se\0"
  "sf_vc_iv_se\0"
  "sf_vc_vv_se\0"
  "sf_vc_fv_se\0"
  "sf_vc_xvv_se\0"
  "sf_vc_ivv_se\0"
  "sf_vc_vvv_se\0"
  "sf_vc_fvv_se\0"
  "sf_vc_v_x_se\0"
  "sf_vc_v_i\0"
  "sf_vc_v_i_se\0"
  "sf_vc_v_xv\0"
  "sf_vc_v_xv_se\0"
  "sf_vc_v_iv\0"
  "sf_vc_v_iv_se\0"
  "sf_vc_v_vv\0"
  "sf_vc_v_vv_se\0"
  "sf_vc_v_fv\0"
  "sf_vc_v_fv_se\0"
  "sf_vc_v_xvv\0"
  "sf_vc_v_xvv_se\0"
  "sf_vc_v_ivv\0"
  "sf_vc_v_ivv_se\0"
  "sf_vc_v_vvv\0"
  "sf_vc_v_vvv_se\0"
  "sf_vc_v_fvv\0"
  "sf_vc_v_fvv_se\0"
  "sf_vc_xvw_se\0"
  "sf_vc_ivw_se\0"
  "sf_vc_vvw_se\0"
  "sf_vc_fvw_se\0"
  "sf_vc_v_xvw\0"
  "sf_vc_v_xvw_se\0"
  "sf_vc_v_ivw\0"
  "sf_vc_v_ivw_se\0"
  "sf_vc_v_vvw\0"
  "sf_vc_v_vvw_se\0"
  "sf_vc_v_fvw\0"
  "sf_vc_v_fvw_se\0"
  "sf_vfnrclip_x_f_qf_rm\0"
  "sf_vfnrclip_x_f_qf_rm_tu\0"
  "sf_vfnrclip_x_f_qf_rm_m\0"
  "sf_vfnrclip_x_f_qf_rm_tum\0"
  "sf_vfnrclip_x_f_qf_rm_tumu\0"
  "sf_vfnrclip_x_f_qf_rm_mu\0"
  "sf_vqmacc_2x8x2\0"
  "sf_vqmacc_2x8x2_tu\0"
  "sf_vqmaccus_2x8x2\0"
  "sf_vqmaccus_2x8x2_tu\0"
  "sf_vqmaccsu_2x8x2\0"
  "sf_vqmaccsu_2x8x2_tu\0"
  "sf_vqmaccu_4x8x4\0"
  "sf_vqmaccu_4x8x4_tu\0"
  "sf_vqmacc_4x8x4\0"
  "sf_vqmacc_4x8x4_tu\0"
  "sf_vqmaccus_4x8x4\0"
  "sf_vqmaccus_4x8x4_tu\0"
  "sf_vqmaccsu_4x8x4\0"
  "sf_vqmaccsu_4x8x4_tu\0"
  "sf_vfexp_v\0"
  "sf_vfexp_v_tu\0"
  "sf_vfexp_v_m\0"
  "sf_vfexp_v_tum\0"
  "sf_vfexp_v_tumu\0"
  "sf_vfexp_v_mu\0"
  "sf_vfexpa_v\0"
  "sf_vfexpa_v_tu\0"
  "sf_vfexpa_v_m\0"
  "sf_vfexpa_v_tum\0"
  "sf_vfexpa_v_tumu\0"
  "sf_vfexpa_v_mu\0"
  "sf_vfwmacc_4x4x4\0"
  "sf_vfwmacc_4x4x4_tu\0"
  "sf_vfnrclip_xu_f_qf_rm\0"
  "sf_vfnrclip_xu_f_qf_rm_tu\0"
  "sf_vfnrclip_xu_f_qf_rm_m\0"
  "sf_vfnrclip_xu_f_qf_rm_tum\0"
  "sf_vfnrclip_xu_f_qf_rm_tumu\0"
  "sf_vfnrclip_xu_f_qf_rm_mu\0"
  "sf_vfnrclip_x_f_qf\0"
  "sf_vfnrclip_x_f_qf_tu\0"
  "sf_vfnrclip_x_f_qf_m\0"
  "sf_vfnrclip_x_f_qf_tum\0"
  "sf_vfnrclip_x_f_qf_tumu\0"
  "sf_vfnrclip_x_f_qf_mu\0"
  "sf_vfnrclip_xu_f_qf\0"
  "sf_vfnrclip_xu_f_qf_tu\0"
  "sf_vfnrclip_xu_f_qf_m\0"
  "sf_vfnrclip_xu_f_qf_tum\0"
  "sf_vfnrclip_xu_f_qf_tumu\0"
  "sf_vfnrclip_xu_f_qf_mu\0"
  "sf_vlte8\0"
  "sf_vtmv_v_t\0"
  "sf_vtzero_t\0"
  "sf_vtdiscard\0"
  "sf_vtmv_t_v\0"
  "sf_vlte16\0"
  "sf_vlte32\0"
  "sf_vlte64\0"
  "sf_vste8\0"
  "sf_vste16\0"
  "sf_vste32\0"
  "sf_vste64\0"
  "sf_mm_u_u_w4\0"
  "sf_mm_s_u_w4\0"
  "sf_mm_u_s_w4\0"
  "sf_mm_s_s_w4\0"
  "sf_mm_f_f_w2\0"
  "sf_mm_f_f_w1\0"
  "sf_mm_e5m2_e5m2_w4\0"
  "sf_mm_e5m2_e4m3_w4\0"
  "sf_mm_e4m3_e5m2_w4\0"
  "sf_mm_e4m3_e4m3_w4\0"
  "sf_vsettk\0"
  "sf_vsettm\0"
  "sf_vsettn\0"
  "sf_vsettnt\0"
  ;
#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif

static constexpr llvm::StringTable
BuiltinStrings = BuiltinStringsStorage;
#endif // GET_RISCVV_BUILTIN_STR_TABLE

// RISCV Vector builtin infos
#ifdef GET_RISCVV_BUILTIN_INFOS
    Builtin::Info{Builtin::Info::StrOffsets{10 /* sf_vqmaccu_2x8x2 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{27 /* sf_vqmaccu_2x8x2_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{47 /* sf_vc_v_x */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{57 /* sf_vc_x_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{68 /* sf_vc_i_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{79 /* sf_vc_xv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{91 /* sf_vc_iv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{103 /* sf_vc_vv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{115 /* sf_vc_fv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{127 /* sf_vc_xvv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{140 /* sf_vc_ivv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{153 /* sf_vc_vvv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{166 /* sf_vc_fvv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{179 /* sf_vc_v_x_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{192 /* sf_vc_v_i */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{202 /* sf_vc_v_i_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{215 /* sf_vc_v_xv */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{226 /* sf_vc_v_xv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{240 /* sf_vc_v_iv */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{251 /* sf_vc_v_iv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{265 /* sf_vc_v_vv */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{276 /* sf_vc_v_vv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{290 /* sf_vc_v_fv */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{301 /* sf_vc_v_fv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{315 /* sf_vc_v_xvv */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{327 /* sf_vc_v_xvv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{342 /* sf_vc_v_ivv */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{354 /* sf_vc_v_ivv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{369 /* sf_vc_v_vvv */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{381 /* sf_vc_v_vvv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{396 /* sf_vc_v_fvv */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{408 /* sf_vc_v_fvv_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{423 /* sf_vc_xvw_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{436 /* sf_vc_ivw_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{449 /* sf_vc_vvw_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{462 /* sf_vc_fvw_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{475 /* sf_vc_v_xvw */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{487 /* sf_vc_v_xvw_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{502 /* sf_vc_v_ivw */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{514 /* sf_vc_v_ivw_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{529 /* sf_vc_v_vvw */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{541 /* sf_vc_v_vvw_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{556 /* sf_vc_v_fvw */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{568 /* sf_vc_v_fvw_se */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{583 /* sf_vfnrclip_x_f_qf_rm */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{605 /* sf_vfnrclip_x_f_qf_rm_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{630 /* sf_vfnrclip_x_f_qf_rm_m */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{654 /* sf_vfnrclip_x_f_qf_rm_tum */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{680 /* sf_vfnrclip_x_f_qf_rm_tumu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{707 /* sf_vfnrclip_x_f_qf_rm_mu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{732 /* sf_vqmacc_2x8x2 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{748 /* sf_vqmacc_2x8x2_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{767 /* sf_vqmaccus_2x8x2 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{785 /* sf_vqmaccus_2x8x2_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{806 /* sf_vqmaccsu_2x8x2 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{824 /* sf_vqmaccsu_2x8x2_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{845 /* sf_vqmaccu_4x8x4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{862 /* sf_vqmaccu_4x8x4_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{882 /* sf_vqmacc_4x8x4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{898 /* sf_vqmacc_4x8x4_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{917 /* sf_vqmaccus_4x8x4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{935 /* sf_vqmaccus_4x8x4_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{956 /* sf_vqmaccsu_4x8x4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{974 /* sf_vqmaccsu_4x8x4_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{995 /* sf_vfexp_v */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1006 /* sf_vfexp_v_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1020 /* sf_vfexp_v_m */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1033 /* sf_vfexp_v_tum */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1048 /* sf_vfexp_v_tumu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1064 /* sf_vfexp_v_mu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1078 /* sf_vfexpa_v */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1090 /* sf_vfexpa_v_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1105 /* sf_vfexpa_v_m */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1119 /* sf_vfexpa_v_tum */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1135 /* sf_vfexpa_v_tumu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1152 /* sf_vfexpa_v_mu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1167 /* sf_vfwmacc_4x4x4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1184 /* sf_vfwmacc_4x4x4_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1204 /* sf_vfnrclip_xu_f_qf_rm */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1227 /* sf_vfnrclip_xu_f_qf_rm_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1253 /* sf_vfnrclip_xu_f_qf_rm_m */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1278 /* sf_vfnrclip_xu_f_qf_rm_tum */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1305 /* sf_vfnrclip_xu_f_qf_rm_tumu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1333 /* sf_vfnrclip_xu_f_qf_rm_mu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1359 /* sf_vfnrclip_x_f_qf */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1378 /* sf_vfnrclip_x_f_qf_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1400 /* sf_vfnrclip_x_f_qf_m */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1421 /* sf_vfnrclip_x_f_qf_tum */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1444 /* sf_vfnrclip_x_f_qf_tumu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1468 /* sf_vfnrclip_x_f_qf_mu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1490 /* sf_vfnrclip_xu_f_qf */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1510 /* sf_vfnrclip_xu_f_qf_tu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1533 /* sf_vfnrclip_xu_f_qf_m */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1555 /* sf_vfnrclip_xu_f_qf_tum */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1579 /* sf_vfnrclip_xu_f_qf_tumu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1604 /* sf_vfnrclip_xu_f_qf_mu */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1627 /* sf_vlte8 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1636 /* sf_vtmv_v_t */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1648 /* sf_vtzero_t */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1660 /* sf_vtdiscard */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1673 /* sf_vtmv_t_v */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1685 /* sf_vlte16 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1695 /* sf_vlte32 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1705 /* sf_vlte64 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1715 /* sf_vste8 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1724 /* sf_vste16 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1734 /* sf_vste32 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1744 /* sf_vste64 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1754 /* sf_mm_u_u_w4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1767 /* sf_mm_s_u_w4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1780 /* sf_mm_u_s_w4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1793 /* sf_mm_s_s_w4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1806 /* sf_mm_f_f_w2 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1819 /* sf_mm_f_f_w1 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1832 /* sf_mm_e5m2_e5m2_w4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1851 /* sf_mm_e5m2_e4m3_w4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1870 /* sf_mm_e4m3_e5m2_w4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1889 /* sf_mm_e4m3_e4m3_w4 */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1908 /* sf_vsettk */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1918 /* sf_vsettm */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1928 /* sf_vsettn */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
    Builtin::Info{Builtin::Info::StrOffsets{1938 /* sf_vsettnt */, 0, 1 /* n */, 3 /* zve32x */}, HeaderDesc::NO_HEADER, ALL_LANGUAGES},
#endif // GET_RISCVV_BUILTIN_INFOS

